import NextTopLoader from 'nextjs-toploader'
import './globals.css'
import Wrapper from '@/Wrapper/Wrapper'
import { ReactLenis } from '@studio-freight/react-lenis'
// import 'remixicon/fonts/remixicon.css'
import 'remixicon/fonts/remixicon.css'

export const metadata = {
  title: 'JS CANDID - Bhopal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
     <html lang="en">
      <body suppressHydrationWarning>
        <Wrapper>
        {/* <NextTopLoader color="rgba(247, 181, 95, 0.753)" /> */}
        <NextTopLoader color="black" />
          {children}
        </Wrapper>
      </body>
    </html>
  )
}
